[package]
name = "central_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.98"
serde = { version = "1.0.219", features = ["derive"] }
clap = { version = "4.5.37", features = ["derive"] }
toml = "0.8.22"
